import catalogData from "@/data/e-numbers.json";

// Curated E-number reference catalogue (src/data/e-numbers.json, generated by
// scripts/e-numre/build_catalog.py). Every entry has its own Danish
// description plus substance-specific sources: the EFSA opinion (DOI) for
// that exact additive where one exists, and research searches on its exact
// substance name. Server-only: the file is ~1-2 MB and must not reach the
// client bundle — clients use /api/additives.

export type ENumberVariant = { code: string; nameDa: string; nameEn: string };
export type ENumberReference = { citation: string; searchTitle: string };
export type ENumberEfsa = {
  title: string;
  url: string;
  date: string;
  adi: string;
  overexposureRisk: string;
};

export type ENumberEntry = {
  code: string;
  nameDa: string;
  nameEn: string;
  category: string;
  classes: string[];
  euStatus: "approved" | "banned" | "not_approved";
  origin: "natural" | "nature_identical" | "synthetic" | "mixed";
  summary: string;
  description: string;
  uses: string;
  health: string;
  research: string;
  keyReferences: ENumberReference[];
  pubmedTerm: string;
  flags: string[];
  variants: ENumberVariant[];
  efsa: ENumberEfsa | null;
  wikipedia: string;
  wikidata: string;
};

const catalog = catalogData as ENumberEntry[];
const byCode = new Map(catalog.map((entry) => [entry.code, entry]));

// "e331iii", "E 331(iii)", "E331III", "en:e331" → "E331(iii)" / "E331".
export function canonicalENumber(raw: string): string {
  let value = raw;
  try {
    value = decodeURIComponent(raw);
  } catch {
    // Malformed escape: keep the raw value.
  }
  value = value.trim().replace(/^en:/i, "").replace(/[\s-]/g, "");
  const match = /^e?(\d{3,4})([a-h]?)\(?([ivx]*)\)?$/i.exec(value);
  if (!match) return value.toUpperCase();
  const [, digits, letter, roman] = match;
  const base = `E${digits}${letter.toLowerCase()}`;
  return roman ? `${base}(${roman.toLowerCase()})` : base;
}

export function listENumbers(): ENumberEntry[] {
  return catalog;
}

// Resolves a code to its catalogue entry; a variant such as E331(iii) resolves
// to its parent E331, whose page describes all variants.
export function findENumber(raw: string): ENumberEntry | null {
  const code = canonicalENumber(raw);
  return byCode.get(code) ?? byCode.get(code.replace(/\(.*\)$/, "")) ?? null;
}

export function eNumberPath(code: string): string {
  return `/e-numre/${encodeURIComponent(canonicalENumber(code).replace(/\(.*\)$/, ""))}`;
}

export type ResearchLink = { label: string; description: string; url: string };

// Links scoped to this exact substance — never generic landing pages.
export function eNumberResearchLinks(entry: ENumberEntry): ResearchLink[] {
  const term = entry.pubmedTerm || `"${entry.nameEn}"`;
  const codeTerm = entry.code.replace(/^E/, "E ");
  const pubmedQuery = `(${term}) AND (food additive OR toxicity OR safety OR health)`;
  const links: ResearchLink[] = [];
  if (entry.efsa?.url) {
    links.push({
      label: `EFSA: ${entry.efsa.title}`,
      description: `EFSA's videnskabelige udtalelse om netop dette stof${
        entry.efsa.date ? ` (${entry.efsa.date.slice(0, 4)})` : ""
      }`,
      url: entry.efsa.url.replace(/^http:\/\/dx\.doi\.org/, "https://doi.org"),
    });
  }
  links.push(
    {
      label: `PubMed: ${entry.nameEn}`,
      description: "Fagfællebedømte studier om stoffets sikkerhed og sundhedseffekter",
      url: `https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent(pubmedQuery)}&sort=date`,
    },
    {
      label: `PubMed-oversigtsartikler: ${entry.nameEn}`,
      description: "Kun reviews og metaanalyser — det samlede overblik over forskningen",
      url: `https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent(term)}&filter=pubt.review&filter=pubt.meta-analysis`,
    },
    {
      label: `EFSA Journal: ${entry.code}`,
      description: "Alle EFSA-udtalelser, der nævner dette E-nummer",
      url: `https://efsa.onlinelibrary.wiley.com/action/doSearch?AllField=${encodeURIComponent(`"${codeTerm}" ${entry.nameEn}`)}`,
    },
    {
      label: `WHO/JECFA: ${entry.nameEn}`,
      description: "FAO/WHO's ekspertkomités toksikologiske vurdering og ADI",
      url: `https://apps.who.int/food-additives-contaminants-jecfa-database/search?q=${encodeURIComponent(entry.nameEn)}`,
    },
    {
      label: `Europe PMC: ${entry.nameEn}`,
      description: "Europæisk forskningsdatabase inkl. fuldtekst-artikler",
      url: `https://europepmc.org/search?query=${encodeURIComponent(term)}`,
    },
  );
  for (const reference of entry.keyReferences) {
    links.push({
      label: reference.citation,
      description: "Nøglestudie — åbner artiklen i PubMed",
      url: `https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent(`${reference.searchTitle}[Title]`)}`,
    });
  }
  links.push({
    label: `Open Food Facts: ${entry.code}`,
    description: "Hvilke produkter stoffet findes i",
    url: `https://world.openfoodfacts.org/facets/additives/${entry.code.toLowerCase()}`,
  });
  if (entry.wikipedia) {
    links.push({ label: "Wikipedia", description: "Opslagsværk (engelsk)", url: entry.wikipedia });
  }
  return links;
}

export const EU_STATUS_LABEL: Record<ENumberEntry["euStatus"], string> = {
  approved: "Godkendt i EU",
  banned: "Forbudt i EU",
  not_approved: "Ikke godkendt i EU",
};

export const ORIGIN_LABEL: Record<ENumberEntry["origin"], string> = {
  natural: "Naturligt udvundet",
  nature_identical: "Naturidentisk",
  synthetic: "Syntetisk",
  mixed: "Naturlig eller syntetisk",
};

export const FLAG_LABEL: Record<string, string> = {
  children_caution: "Børn",
  pregnancy_caution: "Gravide",
  asthma_caution: "Astma",
  kidney_caution: "Nyresygdom",
  pku: "Fenylketonuri (PKU)",
  allergen: "Allergi",
  animal_origin: "Kan være animalsk",
  may_contain_gluten: "Kan indeholde gluten",
  laxative: "Afførende i store mængder",
};
