// "Mad på latin": ordbog over ikke-danske ingrediensnavne (fx dextrose,
// maltodextrin, acerola). Ordene linkes stille i ingredienslister til
// /mad-paa-latin#<anker>. E-numre håndteres separat (src/lib/additives.ts).

export type FoodTerm = {
  term: string;
  /** Andre stavemåder, der også skal linkes. */
  aliases?: string[];
  danish: string;
  explanation: string;
  source: { label: string; href: string };
};

export const FOOD_TERMS: FoodTerm[] = [
  { term: "Acerola", danish: "Acerolakirsebær", explanation: "Acerola (Malpighia emarginata) er et kirsebærlignende bær fra Mellem- og Sydamerika. Det har et af de højeste naturlige indhold af C-vitamin (op til ca. 1,7 g pr. 100 g). I fødevarer bruges acerolapulver især i økologiske pølser og pålæg som naturlig antioxidant, der holder farven og beskytter mod harskning, i stedet for syntetisk ascorbat.", source: { label: "Fødevarestyrelsen: Vitaminer og mineraler", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/saerlige-foedevarekategorier/kosttilskud/vitaminer-og-mineraler-i-kosttilskud" } },
  { term: "Agar", aliases: ["agar-agar"], danish: "Tanggelé", explanation: "Agar er et geleringsmiddel (E406) udvundet af cellevæggene i rødalger. Det danner gelé ved lavere koncentration end gelatine og tåler opvarmning. Bruges i vegetabilske desserter, gelé og slik. Består næsten udelukkende af kostfibre.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Ascorbinsyre", aliases: ["ascorbic acid"], danish: "C-vitamin", explanation: "Ascorbinsyre er det kemiske navn for C-vitamin (E300). Tilsættes enten som vitamin eller som antioxidant, der forhindrer brunfarvning af frugt og nedbrydning af farve i kødvarer. Kroppen kan ikke skelne syntetisk fra naturlig ascorbinsyre.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Caseinat", aliases: ["kaseinat", "natriumcaseinat", "calciumcaseinat"], danish: "Mælkeprotein", explanation: "Caseinat er mælkeproteinet kasein bundet til natrium eller kalium/calcium. Det er vandopløseligt og bruges som emulgator, skumdanner og proteinkilde i fx kaffefløde, pålæg og proteinprodukter. Indeholder mælk og er relevant for mælkeallergikere, selvom varen kaldes 'laktosefri'.", source: { label: "Fødevarestyrelsen: Oplysning om allergener", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/maerkning-og-markedsfoering-af-foedevarer/generelle-maerkningskrav/oplysning-om-allergener" } },
  { term: "Dextrose", aliases: ["dekstrose"], danish: "Druesukker (glukose)", explanation: "Dextrose er den kemiske betegnelse for glukose (druesukker), oftest fremstillet ved at nedbryde majs- eller hvedestivelse. I pølser og spegepølse bruges det som næring for modningskulturerne, til smag og til at stabilisere farven. Det hæver blodsukkeret hurtigere end almindeligt sukker (glykæmisk indeks 100).", source: { label: "Fødevarestyrelsen: Kostråd om sukker", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/alt-om-mad/de-officielle-kostraad/kostraad-til-dig/om-de-officielle-kostraad/spis-mindre-af-det-soede-salte-og-fede" } },
  { term: "Erythritol", danish: "Sukkeralkohol", explanation: "Erythritol (E968) er en sukkeralkohol, der findes naturligt i frugt og fremstilles ved gæring. Det giver næsten ingen kalorier og påvirker ikke blodsukkeret. Et amerikansk studie (Witkowski m.fl., Nature Medicine 2023) fandt sammenhæng mellem højt erythritolniveau i blodet og hjerte-kar-hændelser; det er observationelt og ikke bevist årsagssammenhæng.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Fruktose", aliases: ["fructose"], danish: "Frugtsukker", explanation: "Fruktose (frugtsukker) er en enkel sukkerart fra frugt, honning og halvdelen af almindeligt sukker. Omsættes primært i leveren. Stort indtag af tilsat fruktose, fx via sirupper, er forbundet med fedtlever og forhøjede blodfedtstoffer.", source: { label: "Fødevarestyrelsen: Kostråd om sukker", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/alt-om-mad/de-officielle-kostraad/kostraad-til-dig/om-de-officielle-kostraad/spis-mindre-af-det-soede-salte-og-fede" } },
  { term: "Glukose", aliases: ["glucose"], danish: "Druesukker", explanation: "Glukose (druesukker) er kroppens vigtigste energikilde og den sukkerart, blodsukkeret måles i. I ingredienslister stammer den oftest fra nedbrudt stivelse. Samme stof som dextrose.", source: { label: "Fødevarestyrelsen: Kostråd om sukker", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/alt-om-mad/de-officielle-kostraad/kostraad-til-dig/om-de-officielle-kostraad/spis-mindre-af-det-soede-salte-og-fede" } },
  { term: "Glukosesirup", aliases: ["glucosesirup", "glukose-fruktosesirup", "glucose-fructose sirup"], danish: "Stivelsessirup", explanation: "Glukosesirup fremstilles ved at nedbryde stivelse fra majs, hvede eller kartoffel til en blanding af glukose, maltose og længere kæder. Bruges i slik, is og bagværk for sødme, glans og for at hindre krystallisering. Kaldes 'glukose-fruktosesirup', når over 5 % er fruktose.", source: { label: "Fødevarestyrelsen: Kostråd om sukker", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/alt-om-mad/de-officielle-kostraad/kostraad-til-dig/om-de-officielle-kostraad/spis-mindre-af-det-soede-salte-og-fede" } },
  { term: "Inulin", danish: "Kostfiber", explanation: "Inulin er en opløselig kostfiber, oftest udvundet af cikorierod. Den fordøjes ikke i tyndtarmen, men fermenteres af tarmbakterier og virker præbiotisk. Bruges til at øge fiberindholdet og erstatte fedt eller sukker. Store mængder kan give luft og oppustethed.", source: { label: "Fødevarestyrelsen: Kostråd om fuldkorn og fibre", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/alt-om-mad/de-officielle-kostraad/kostraad-til-dig/om-de-officielle-kostraad/spis-mad-med-fuldkorn" } },
  { term: "Isomalt", danish: "Sukkeralkohol", explanation: "Isomalt (E953) er en sukkeralkohol fremstillet af roesukker. Den giver ca. halvt så mange kalorier som sukker, skader ikke tænderne og bruges i sukkerfri bolsjer og kagepynt. Kan virke afførende ved større indtag.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Laktose", aliases: ["lactose"], danish: "Mælkesukker", explanation: "Laktose (mælkesukker) består af glukose og galaktose. Personer med laktoseintolerans mangler enzymet laktase og kan få maveproblemer. Bruges også som fyldstof og bærestof i fx krydderiblandinger og pålæg.", source: { label: "Fødevarestyrelsen: Kostråd om sukker", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/alt-om-mad/de-officielle-kostraad/kostraad-til-dig/om-de-officielle-kostraad/spis-mindre-af-det-soede-salte-og-fede" } },
  { term: "Lecithin", aliases: ["lecitin", "sojalecithin", "solsikkelecithin"], danish: "Emulgator", explanation: "Lecithin (E322) er en gruppe fedtstoffer (fosfolipider) fra soja, solsikke eller æg. Den virker som emulgator, der får fedt og vand til at blande sig, fx i chokolade og margarine. Sojalecithin skal mærkes som allergen (soja).", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Maltodextrin", aliases: ["maltodekstrin"], danish: "Nedbrudt stivelse", explanation: "Maltodextrin er et kulhydrat fremstillet ved delvis nedbrydning af stivelse (majs, kartoffel, hvede eller ris). Det er næsten smagløst, opløses let og bruges som fyld, bærestof for aromaer og til konsistens i fx supper, sportsdrikke og krydderier. Det optages meget hurtigt og har et højt glykæmisk indeks.", source: { label: "Fødevarestyrelsen: Kostråd om sukker", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/alt-om-mad/de-officielle-kostraad/kostraad-til-dig/om-de-officielle-kostraad/spis-mindre-af-det-soede-salte-og-fede" } },
  { term: "Maltose", danish: "Maltsukker", explanation: "Maltose (maltsukker) består af to glukoseenheder og dannes, når stivelse nedbrydes, fx ved maltning af korn til øl. Findes i glukosesirup og maltekstrakt. Omdannes til glukose i kroppen.", source: { label: "Fødevarestyrelsen: Kostråd om sukker", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/alt-om-mad/de-officielle-kostraad/kostraad-til-dig/om-de-officielle-kostraad/spis-mindre-af-det-soede-salte-og-fede" } },
  { term: "Maltitol", danish: "Sukkeralkohol", explanation: "Maltitol (E965) er en sukkeralkohol fremstillet af maltose. Smager næsten som sukker og bruges i sukkerfri chokolade. Påvirker blodsukkeret mere end andre sukkeralkoholer og kan virke afførende; produkter med over 10 % skal mærkes med advarsel.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Pektin", aliases: ["pectin"], danish: "Frugtgelé", explanation: "Pektin (E440) er et geleringsmiddel fra cellevæggene i frugt, især æbler og citrusskaller. Bruges i marmelade, syltetøj og vingummi. Er en opløselig kostfiber.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Polydextrose", danish: "Syntetisk kostfiber", explanation: "Polydextrose (E1200) er en syntetisk kostfiber fremstillet af glukose, sorbitol og citronsyre. Giver kun ca. 1 kcal/g og bruges som fyld i kalorie- og sukkerreducerede produkter.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Sorbitol", danish: "Sukkeralkohol", explanation: "Sorbitol (E420) er en sukkeralkohol, der findes naturligt i blommer og æbler. Bruges som sødemiddel og til at holde på fugten i bagværk og slik. Kan virke afførende; kræver advarsel ved over 10 %.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Stevia", aliases: ["steviolglykosider"], danish: "Sødeblad", explanation: "Steviolglykosider (E960) er søde stoffer fra bladene af Stevia rebaudiana. Op til 300 gange sødere end sukker og kaloriefrie. Kan have en let lakridsagtig eftersmag.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Sucralose", aliases: ["sukralose"], danish: "Kunstigt sødemiddel", explanation: "Sucralose (E955) er et sødemiddel fremstillet ved at klorere sukker. Ca. 600 gange sødere end sukker og kaloriefrit. Tåler opvarmning. Nyere forskning undersøger mulige effekter på tarmfloraen.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Xanthan", aliases: ["xanthangummi", "xanthan gum"], danish: "Fortykningsmiddel", explanation: "Xanthangummi (E415) fremstilles ved at lade bakterien Xanthomonas campestris gære sukker. Giver tyktflydende konsistens i meget små mængder og bruges i dressinger, saucer og glutenfrit bagværk.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Xylitol", danish: "Birkesukker", explanation: "Xylitol (E967) er en sukkeralkohol, oprindeligt fra birketræ. Den forebygger huller i tænderne og bruges i tyggegummi og pastiller. Kan virke afførende. Meget giftig for hunde.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Psyllium", aliases: ["psylliumskaller", "loppefrøskaller"], danish: "Loppefrøskaller", explanation: "Psyllium er skallerne fra frø af plantago-planten (loppefrø). De binder store mængder vand og danner gel. Bruges i glutenfrit brød som bindemiddel og som afføringsregulerende fibertilskud. Drik rigeligt vand ved indtag.", source: { label: "Fødevarestyrelsen: Kostråd om fuldkorn og fibre", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/alt-om-mad/de-officielle-kostraad/kostraad-til-dig/om-de-officielle-kostraad/spis-mad-med-fuldkorn" } },
  { term: "Carrageenan", aliases: ["carrageen", "karragenan"], danish: "Tangekstrakt", explanation: "Carrageenan (E407) er et fortykningsmiddel fra rødalger, som giver cremet konsistens i mejeriprodukter, desserter og plantedrikke. EFSA har vurderet stoffet sikkert, men anbefalet mere forskning i effekter på tarmen; det er ikke tilladt i modermælkserstatning.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Mannitol", danish: "Sukkeralkohol", explanation: "Mannitol (E421) er en sukkeralkohol, der findes naturligt i svampe og tang. Bruges i tyggegummi og som pudder på slik. Har tydeligt afførende virkning og bruges også medicinsk.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Aspartam", aliases: ["aspartame"], danish: "Kunstigt sødemiddel", explanation: "Aspartam (E951) er et sødemiddel ca. 200 gange sødere end sukker, opbygget af aminosyrerne asparaginsyre og phenylalanin. Personer med PKU (phenylketonuri) skal undgå det, derfor mærkningen 'indeholder en kilde til phenylalanin'. WHO's kræftagentur IARC klassificerede det i 2023 som 'muligvis kræftfremkaldende' (gruppe 2B), mens JECFA og EFSA fastholder, at det er sikkert inden for ADI på 40 mg/kg kropsvægt.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Acesulfam", aliases: ["acesulfam-k", "acesulfam k"], danish: "Kunstigt sødemiddel", explanation: "Acesulfam K (E950) er et syntetisk sødemiddel ca. 200 gange sødere end sukker. Det optages ikke og udskilles uændret, så det giver ingen kalorier. Bruges ofte sammen med aspartam eller sucralose i light-drikke. EFSA revurderede stoffet i 2025 og fastholdt det som sikkert inden for det acceptable daglige indtag (ADI).", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Oligofruktose", aliases: ["oligofructose", "fruktooligosakkarider"], danish: "Kostfiber", explanation: "Oligofruktose er korte kæder af fruktose, typisk fra cikorierod. Den virker som kostfiber og præbiotikum ligesom inulin, men smager let sødt. Store mængder kan give luft i maven.", source: { label: "Fødevarestyrelsen: Kostråd om fuldkorn og fibre", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/alt-om-mad/de-officielle-kostraad/kostraad-til-dig/om-de-officielle-kostraad/spis-mad-med-fuldkorn" } },
  { term: "Trehalose", danish: "Svampesukker", explanation: "Trehalose er en sukkerart af to glukoseenheder, som findes i svampe og gær. Den er halvt så sød som sukker og bruges til at bevare konsistens ved frysning og tørring.", source: { label: "Fødevarestyrelsen: Kostråd om sukker", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/alt-om-mad/de-officielle-kostraad/kostraad-til-dig/om-de-officielle-kostraad/spis-mindre-af-det-soede-salte-og-fede" } },
  { term: "Dextrin", aliases: ["dekstrin"], danish: "Nedbrudt stivelse", explanation: "Dextrin er stivelse, der er delvist nedbrudt med varme eller syre til kortere kulhydratkæder. Bruges som bindemiddel, til sprøde overflader og som bærestof for aromaer. Fordøjes som almindelig stivelse.", source: { label: "Fødevarestyrelsen: Kostråd om sukker", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/alt-om-mad/de-officielle-kostraad/kostraad-til-dig/om-de-officielle-kostraad/spis-mindre-af-det-soede-salte-og-fede" } },
  { term: "Tokoferol", aliases: ["tocopherol", "tokoferoler", "tocopheroler"], danish: "E-vitamin", explanation: "Tokoferoler er E-vitamin (E306–E309). Tilsættes som antioxidant, der beskytter olier og fedt mod harskning, og som vitamin.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Riboflavin", danish: "B2-vitamin", explanation: "Riboflavin er B2-vitamin, som også bruges som gult farvestof (E101). Vigtig for energiomsætningen. Overskud udskilles med urinen, der kan blive knaldgul.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
  { term: "Thiamin", danish: "B1-vitamin", explanation: "Thiamin er B1-vitamin, nødvendig for omsætningen af kulhydrat. Tilsættes berigede kornprodukter.", source: { label: "Fødevarestyrelsen: Vitaminer og mineraler", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/saerlige-foedevarekategorier/kosttilskud/vitaminer-og-mineraler-i-kosttilskud" } },
  { term: "Pyridoxin", danish: "B6-vitamin", explanation: "Pyridoxin er en form af B6-vitamin, vigtig for proteinomsætning og nervesystem. Tilsættes berigede produkter. Meget høje doser over længere tid kan give nerveskader.", source: { label: "Fødevarestyrelsen: Vitaminer og mineraler", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/saerlige-foedevarekategorier/kosttilskud/vitaminer-og-mineraler-i-kosttilskud" } },
  { term: "Cyanocobalamin", aliases: ["cobalamin", "kobalamin"], danish: "B12-vitamin", explanation: "Cyanocobalamin er den syntetiske, stabile form af B12-vitamin. Tilsættes plantedrikke, morgenmadsprodukter og vegetarprodukter, fordi B12 naturligt næsten kun findes i animalske fødevarer. Nødvendigt for dannelse af røde blodlegemer og nervesystemet.", source: { label: "Fødevarestyrelsen: Vitaminer og mineraler", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/saerlige-foedevarekategorier/kosttilskud/vitaminer-og-mineraler-i-kosttilskud" } },
  { term: "Kolekalciferol", aliases: ["cholecalciferol"], danish: "D3-vitamin", explanation: "Kolekalciferol er D3-vitamin, samme form som huden danner i sollys. Tilsættes fx mælk, margarine og plantedrikke. Sundhedsstyrelsen anbefaler tilskud i vinterhalvåret for mange grupper.", source: { label: "Fødevarestyrelsen: Vitaminer og mineraler", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/saerlige-foedevarekategorier/kosttilskud/vitaminer-og-mineraler-i-kosttilskud" } },
  { term: "Retinol", aliases: ["retinylacetat", "retinylpalmitat"], danish: "A-vitamin", explanation: "Retinol er den aktive form af A-vitamin, vigtig for syn, hud og immunforsvar. Tilsættes margarine og berigede produkter. Gravide bør undgå højt indtag.", source: { label: "Fødevarestyrelsen: Vitaminer og mineraler", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/saerlige-foedevarekategorier/kosttilskud/vitaminer-og-mineraler-i-kosttilskud" } },
  { term: "Betakaroten", aliases: ["betacaroten", "beta-caroten", "betakarotin"], danish: "Gulerodsfarve", explanation: "Betakaroten er det orange farvestof i gulerødder og græskar (E160a). Kroppen omdanner det til A-vitamin efter behov. Bruges som farvestof i fx margarine, ost og drikke. Højdosis-tilskud frarådes rygere.", source: { label: "Fødevarestyrelsen: Tilsætningsstoffer", href: "https://foedevarestyrelsen.dk/kost-og-foedevarer/foedevaresikkerhed/tilsaetninger/tilsaetningsstoffer" } },
];

export function foodTermAnchor(term: string): string {
  return term
    .toLowerCase()
    .replace(/æ/g, "ae")
    .replace(/ø/g, "oe")
    .replace(/å/g, "aa")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function foodTermHref(term: string): string {
  return `/mad-paa-latin#${foodTermAnchor(term)}`;
}

export function matchesFoodTerm(item: FoodTerm, query: string): boolean {
  const q = query.trim().toLowerCase();
  if (!q) return true;
  return [item.term, item.danish, item.explanation, ...(item.aliases ?? [])].some((text) =>
    text.toLowerCase().includes(q),
  );
}

export type FoodTermPart = { text: string; term?: string };

const escape = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

// Længste navn først, så "glukosesirup" vinder over "glukose".
const LOOKUP = new Map<string, string>();
for (const item of FOOD_TERMS) {
  for (const name of [item.term, ...(item.aliases ?? [])]) LOOKUP.set(name.toLowerCase(), item.term);
}
const PATTERN = new RegExp(
  `(?<![\\p{L}\\d])(${[...LOOKUP.keys()].sort((a, b) => b.length - a.length).map(escape).join("|")})(?![\\p{L}\\d])`,
  "giu",
);

// Deler en ingredienstekst op i almindelig tekst og ordbogsord.
export function splitFoodTerms(text: string): FoodTermPart[] {
  const parts: FoodTermPart[] = [];
  let last = 0;
  for (const match of text.matchAll(PATTERN)) {
    const start = match.index ?? 0;
    if (start > last) parts.push({ text: text.slice(last, start) });
    parts.push({ text: match[0], term: LOOKUP.get(match[0].toLowerCase()) });
    last = start + match[0].length;
  }
  if (last < text.length) parts.push({ text: text.slice(last) });
  return parts;
}
