-- Godkendte synonymforslag (docs/SYNONYM-FORSLAG.md, 2026-10-09)
INSERT INTO "search_synonyms" ("id", "language", "termA", "termB", "similarity", "updatedAt") VALUES
  (gen_random_uuid()::text, 'DA', 'grisekød', 'svinekød', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'salami', 'spegepølse', 60, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'frikadeller', 'kødboller', 60, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'leverpostej', 'paté', 60, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'kogt skinke', 'skinke', 90, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'hotdogbrød', 'pølsebrød', 90, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'ipa', 'pale ale', 70, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'lager', 'pilsner', 80, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'hvedeøl', 'weissbier', 90, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'rosé', 'rosévin', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'champagne', 'mousserende vin', 60, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'cava', 'mousserende vin', 70, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'mousserende vin', 'prosecco', 70, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'akvavit', 'snaps', 90, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'læskedrik', 'sodavand', 90, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'brus', 'sodavand', 90, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'cola', 'sodavand', 50, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'kildevand', 'mineralvand', 80, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'kildevand', 'vand', 70, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'drikkevand', 'vand', 90, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'juice', 'saft', 50, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'saft', 'saftevand', 60, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'ice tea', 'iste', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'læskedrik', 'læskedrikskoncentrat', 50, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'chips', 'kartoffelchips', 90, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'chips', 'snack', 50, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'fritter', 'pommes frites', 90, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'flødeis', 'is', 70, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'isbar', 'ispinde', 80, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'bolcher', 'bolsjer', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'choko', 'chokolade', 80, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'konfekt', 'slik', 60, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'biscuit', 'kiks', 80, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'cookies', 'småkager', 80, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'cookie', 'småkage', 90, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'yoghurt', 'yogurt', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'kærnemælk', 'syrnet mælk', 60, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'fløde', 'piskefløde', 90, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'fløde', 'madlavningsfløde', 50, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'mælk', 'sødmælk', 70, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'letmælk', 'minimælk', 30, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'skyr', 'ymer', 30, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'mysli', 'müsli', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'musli', 'müsli', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'granola', 'müsli', 70, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'havreflager', 'havregryn', 80, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'cornflakes', 'morgenmadsprodukt', 60, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'ketchup', 'tomatketchup', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'remolade', 'remoulade', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'chili sauce', 'chilisauce', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'grøn pesto', 'pesto', 80, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'salsa', 'tomatsalsa', 80, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'dressing', 'sauce', 30, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'jordnødder', 'peanuts', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'jordnøddesmør', 'peanutbutter', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'pasta', 'spaghetti', 70, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'nudler', 'pasta', 40, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'instant nudler', 'nudler', 60, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'hvedemel', 'mel', 70, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'rørsukker', 'sukker', 50, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'kaffekapsler', 'kapsler', 70, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'te', 'urtete', 50, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'løg', 'rødløg', 50, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'postevand', 'vand', 90, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'flaskevand', 'vand', 90, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'mineralvand', 'vand', 70, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'mineralvand', 'naturligt mineralvand', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'drikkevand', 'postevand', 80, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'flaskevand', 'kildevand', 70, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'flaskevand', 'mineralvand', 70, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'cookie dough', 'cookiedough', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'charlotteløg', 'skalotteløg', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'charlotte løg', 'charlotteløg', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'te', 'the', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'barbecue', 'bbq', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'sauce', 'sovs', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'weissbier', 'weizenbier', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'weissbier', 'weizen', 100, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'DA', 'hvedeøl', 'weizen', 90, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
