// GENERATED by scripts/native/sync.mjs from the web app — do not edit by hand.
import SwiftUI

/// Colours from src/app/globals.css :root (--hf-color-*).
enum HcColors {
    /// --hf-color-page
    static let page = Color(.sRGB, red: 0.9804, green: 0.9725, blue: 0.9529, opacity: 1.0000)
    /// --hf-color-surface
    static let surface = Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1.0000)
    /// --hf-color-card
    static let card = Color(.sRGB, red: 0.9333, green: 0.9137, blue: 0.8745, opacity: 1.0000)
    /// --hf-color-nav
    static let nav = Color(.sRGB, red: 0.8745, green: 0.8510, blue: 0.8000, opacity: 1.0000)
    /// --hf-white
    static let white = Color(.sRGB, red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1.0000)
    /// --hf-color-brand
    static let brand = Color(.sRGB, red: 0.0235, green: 0.4784, blue: 0.2745, opacity: 1.0000)
    /// --hf-color-brand-dark
    static let brandDark = Color(.sRGB, red: 0.0118, green: 0.3373, blue: 0.1412, opacity: 1.0000)
    /// --hf-color-accent
    static let accent = Color(.sRGB, red: 0.7333, green: 0.9412, blue: 0.4157, opacity: 1.0000)
    /// --hf-color-appbar
    static let appbar = Color(.sRGB, red: 0.0235, green: 0.4784, blue: 0.2745, opacity: 1.0000)
    /// --hf-color-progress
    static let progress = Color(.sRGB, red: 0.0235, green: 0.4784, blue: 0.2745, opacity: 1.0000)
    /// --hf-color-progress-dark
    static let progressDark = Color(.sRGB, red: 0.0118, green: 0.3373, blue: 0.1412, opacity: 1.0000)
    /// --hf-color-selected-bg
    static let selectedBg = Color(.sRGB, red: 0.7333, green: 0.9412, blue: 0.4157, opacity: 1.0000)
    /// --hf-color-selected-border
    static let selectedBorder = Color(.sRGB, red: 0.1373, green: 0.1373, blue: 0.1373, opacity: 1.0000)
    /// --hf-color-selected-text
    static let selectedText = Color(.sRGB, red: 0.1373, green: 0.1373, blue: 0.1373, opacity: 1.0000)
    /// --hf-color-text
    static let text = Color(.sRGB, red: 0.1373, green: 0.1373, blue: 0.1373, opacity: 1.0000)
    /// --hf-color-action
    static let action = Color(.sRGB, red: 0.1373, green: 0.1373, blue: 0.1373, opacity: 1.0000)
    /// --hf-color-action-hover
    static let actionHover = Color(.sRGB, red: 0.2078, green: 0.2078, blue: 0.2078, opacity: 1.0000)
    /// --hf-color-action-active
    static let actionActive = Color(.sRGB, red: 0.2941, green: 0.2941, blue: 0.2941, opacity: 1.0000)
    /// --hf-color-secondary-hover
    static let secondaryHover = Color(.sRGB, red: 0.8902, green: 0.8902, blue: 0.8902, opacity: 1.0000)
    /// --hf-color-secondary-active
    static let secondaryActive = Color(.sRGB, red: 0.8235, green: 0.8235, blue: 0.8235, opacity: 1.0000)
    /// --hf-color-text-secondary
    static let textSecondary = Color(.sRGB, red: 0.3961, green: 0.3961, blue: 0.3961, opacity: 1.0000)
    /// --hf-color-inactive
    static let inactive = Color(.sRGB, red: 0.5098, green: 0.5098, blue: 0.5098, opacity: 1.0000)
    /// --hf-color-placeholder
    static let placeholder = Color(.sRGB, red: 0.7569, green: 0.7529, blue: 0.7451, opacity: 1.0000)
    /// --hf-color-disabled
    static let disabled = Color(.sRGB, red: 0.6510, green: 0.6353, blue: 0.6235, opacity: 1.0000)
    /// --hf-color-line
    static let line = Color(.sRGB, red: 0.6863, green: 0.6784, blue: 0.6667, opacity: 1.0000)
    /// --hf-color-field-border
    static let fieldBorder = Color(.sRGB, red: 0.4902, green: 0.4588, blue: 0.3804, opacity: 1.0000)
    /// --hf-color-field-hover
    static let fieldHover = Color(.sRGB, red: 0.3804, green: 0.3608, blue: 0.3137, opacity: 1.0000)
    /// --hf-color-field-focus
    static let fieldFocus = Color(.sRGB, red: 0.2902, green: 0.2745, blue: 0.2392, opacity: 1.0000)
    /// --hf-color-google
    static let google = Color(.sRGB, red: 0.2588, green: 0.5216, blue: 0.9569, opacity: 1.0000)
    /// --hf-color-facebook
    static let facebook = Color(.sRGB, red: 0.0000, green: 0.0902, blue: 0.5490, opacity: 1.0000)
    /// --hf-color-positive
    static let positive = Color(.sRGB, red: 0.7333, green: 0.9412, blue: 0.4157, opacity: 1.0000)
    /// --hf-color-danger
    static let danger = Color(.sRGB, red: 0.6392, green: 0.1529, blue: 0.1216, opacity: 1.0000)
    /// --hf-color-warning
    static let warning = Color(.sRGB, red: 0.5412, green: 0.3529, blue: 0.0000, opacity: 1.0000)
    /// --hf-color-warning-fill
    static let warningFill = Color(.sRGB, red: 0.9490, green: 0.7608, blue: 0.1882, opacity: 1.0000)
    /// --hf-color-warning-bg
    static let warningBg = Color(.sRGB, red: 0.9922, green: 0.9529, blue: 0.8275, opacity: 1.0000)
    /// --hf-color-overlay
    static let overlay = Color(.sRGB, red: 0.1373, green: 0.1373, blue: 0.1373, opacity: 0.4000)
    /// --hf-color-watch
    static let watch = Color(.sRGB, red: 0.1843, green: 0.5020, blue: 0.9294, opacity: 1.0000)
    /// --hf-color-faceid
    static let faceid = Color(.sRGB, red: 0.0392, green: 0.4784, blue: 1.0000, opacity: 1.0000)
    /// --hf-color-faceid-spin
    static let faceidSpin = Color(.sRGB, red: 0.2078, green: 0.7686, blue: 0.8314, opacity: 1.0000)
    /// --mk-color-brand-light
    static let mkBrandLight = Color(.sRGB, red: 0.0392, green: 0.5608, blue: 0.3255, opacity: 1.0000)
    /// --hf-color-skeleton
    static let skeleton = Color(.sRGB, red: 0.8863, green: 0.8549, blue: 0.7961, opacity: 1.0000)
    /// --hf-color-skeleton-highlight
    static let skeletonHighlight = Color(.sRGB, red: 0.9490, green: 0.9333, blue: 0.9020, opacity: 1.0000)
    /// --hf-green
    static let green = Color(.sRGB, red: 0.0235, green: 0.4784, blue: 0.2745, opacity: 1.0000)
    /// --hf-green-dark
    static let greenDark = Color(.sRGB, red: 0.0118, green: 0.3373, blue: 0.1412, opacity: 1.0000)
    /// --hf-green-light
    static let greenLight = Color(.sRGB, red: 0.7333, green: 0.9412, blue: 0.4157, opacity: 1.0000)
    /// --hf-cream
    static let cream = Color(.sRGB, red: 0.9804, green: 0.9725, blue: 0.9529, opacity: 1.0000)
    /// --hf-tan
    static let tan = Color(.sRGB, red: 0.9333, green: 0.9137, blue: 0.8745, opacity: 1.0000)
    /// --hf-tan-dark
    static let tanDark = Color(.sRGB, red: 0.8745, green: 0.8510, blue: 0.8000, opacity: 1.0000)
    /// --hf-black
    static let black = Color(.sRGB, red: 0.1373, green: 0.1373, blue: 0.1373, opacity: 1.0000)
    /// --hf-gray-light
    static let grayLight = Color(.sRGB, red: 0.8745, green: 0.8510, blue: 0.8000, opacity: 1.0000)
    /// --hf-gray
    static let gray = Color(.sRGB, red: 0.5098, green: 0.5098, blue: 0.5098, opacity: 1.0000)
    /// --hf-gray-dark
    static let grayDark = Color(.sRGB, red: 0.3961, green: 0.3961, blue: 0.3961, opacity: 1.0000)
    /// --hf-red-dark
    static let redDark = Color(.sRGB, red: 0.6392, green: 0.1529, blue: 0.1216, opacity: 1.0000)
    /// --hf-green-muted
    static let greenMuted = Color(.sRGB, red: 0.4353, green: 0.6471, blue: 0.5176, opacity: 1.0000)
    /// --hf-red-muted
    static let redMuted = Color(.sRGB, red: 0.7255, green: 0.5020, blue: 0.4667, opacity: 1.0000)
    /// --hf-gray-border
    static let grayBorder = Color(.sRGB, red: 0.6863, green: 0.6784, blue: 0.6667, opacity: 1.0000)
    /// --hf-fab
    static let fab = Color(.sRGB, red: 0.1373, green: 0.1373, blue: 0.1373, opacity: 1.0000)
    /// --hf-lime
    static let lime = Color(.sRGB, red: 0.7333, green: 0.9412, blue: 0.4157, opacity: 1.0000)
    /// --hf-meat
    static let meat = Color(.sRGB, red: 0.5490, green: 0.3529, blue: 0.1961, opacity: 1.0000)
}

/// Text roles (.hf-type-*): size, weight, line height.
enum HcType {
    /// .hf-type-hero
    static let hero = Font.system(size: 32, weight: .bold)
    /// .hf-type-page-title
    static let pageTitle = Font.system(size: 22, weight: .bold)
    /// .hf-type-title
    static let title = Font.system(size: 17, weight: .bold)
    /// .hf-type-card-title
    static let cardTitle = Font.system(size: 17, weight: .bold)
    /// .hf-type-nav-title
    static let navTitle = Font.system(size: 17, weight: .bold)
    /// .hf-type-body-lg
    static let bodyLg = Font.system(size: 17, weight: .regular)
    /// .hf-type-button
    static let button = Font.system(size: 17, weight: .bold)
    /// .hf-type-input
    static let input = Font.system(size: 17, weight: .regular)
    /// .hf-type-body
    static let body = Font.system(size: 15, weight: .regular)
    /// .hf-type-section-title
    static let sectionTitle = Font.system(size: 15, weight: .bold)
    /// .hf-type-small
    static let small = Font.system(size: 13, weight: .regular)
    /// .hf-type-caption
    static let caption = Font.system(size: 13, weight: .regular)
    /// .hf-type-label
    static let label = Font.system(size: 13, weight: .regular)
    /// .hf-type-progress-active
    static let progressActive = Font.system(size: 13, weight: .bold)
    /// .hf-type-progress-inactive
    static let progressInactive = Font.system(size: 13, weight: .regular)
    /// .hf-type-micro
    static let micro = Font.system(size: 11, weight: .regular)
    /// .hf-type-tab
    static let tab = Font.system(size: 11, weight: .regular)
}
