-- Ental/flertal på generiske ingredienser (docs/REGLER.md): søgning efter
-- "et æble" må ikke give "æbler". Begge felter udfyldes; ens tekst hvor formen
-- ikke kan afgøres (fx æg). Kendte hele navne får rigtige former, resten
-- kopieres fra name og kan forfines senere.
ALTER TABLE "generic_ingredients" ADD COLUMN "nameSingular" TEXT;
ALTER TABLE "generic_ingredients" ADD COLUMN "namePlural" TEXT;

UPDATE "generic_ingredients" g
SET "nameSingular" = CASE WHEN left(g."name", 1) = upper(left(g."name", 1)) THEN upper(left(f.singular, 1)) || substr(f.singular, 2) ELSE f.singular END,
    "namePlural"   = CASE WHEN left(g."name", 1) = upper(left(g."name", 1)) THEN upper(left(f.plural, 1)) || substr(f.plural, 2) ELSE f.plural END
FROM (VALUES
  ('abrikos', 'abrikos', 'abrikoser'),
  ('abrikoser', 'abrikos', 'abrikoser'),
  ('agurk', 'agurk', 'agurker'),
  ('agurker', 'agurk', 'agurker'),
  ('ananas', 'ananas', 'ananasser'),
  ('ananasser', 'ananas', 'ananasser'),
  ('appelsin', 'appelsin', 'appelsiner'),
  ('appelsiner', 'appelsin', 'appelsiner'),
  ('aubergine', 'aubergine', 'auberginer'),
  ('auberginer', 'aubergine', 'auberginer'),
  ('avocado', 'avocado', 'avocadoer'),
  ('avocadoer', 'avocado', 'avocadoer'),
  ('banan', 'banan', 'bananer'),
  ('bananer', 'banan', 'bananer'),
  ('blomme', 'blomme', 'blommer'),
  ('blommer', 'blomme', 'blommer'),
  ('bønne', 'bønne', 'bønner'),
  ('bønner', 'bønne', 'bønner'),
  ('citron', 'citron', 'citroner'),
  ('citroner', 'citron', 'citroner'),
  ('clementin', 'clementin', 'clementiner'),
  ('clementiner', 'clementin', 'clementiner'),
  ('dadel', 'dadel', 'dadler'),
  ('dadler', 'dadel', 'dadler'),
  ('drue', 'drue', 'druer'),
  ('druer', 'drue', 'druer'),
  ('fersken', 'fersken', 'ferskner'),
  ('ferskner', 'fersken', 'ferskner'),
  ('figen', 'figen', 'figner'),
  ('figner', 'figen', 'figner'),
  ('granatæble', 'granatæble', 'granatæbler'),
  ('granatæbler', 'granatæble', 'granatæbler'),
  ('grapefrugt', 'grapefrugt', 'grapefrugter'),
  ('grapefrugter', 'grapefrugt', 'grapefrugter'),
  ('gulerod', 'gulerod', 'gulerødder'),
  ('gulerødder', 'gulerod', 'gulerødder'),
  ('kartoffel', 'kartoffel', 'kartofler'),
  ('kartofler', 'kartoffel', 'kartofler'),
  ('kantarel', 'kantarel', 'kantareller'),
  ('kantareller', 'kantarel', 'kantareller'),
  ('kikært', 'kikært', 'kikærter'),
  ('kikærter', 'kikært', 'kikærter'),
  ('kiwi', 'kiwi', 'kiwier'),
  ('kiwier', 'kiwi', 'kiwier'),
  ('mango', 'mango', 'mangoer'),
  ('mangoer', 'mango', 'mangoer'),
  ('nektarin', 'nektarin', 'nektariner'),
  ('nektariner', 'nektarin', 'nektariner'),
  ('pastinak', 'pastinak', 'pastinakker'),
  ('pastinakker', 'pastinak', 'pastinakker'),
  ('peberfrugt', 'peberfrugt', 'peberfrugter'),
  ('peberfrugter', 'peberfrugt', 'peberfrugter'),
  ('pære', 'pære', 'pærer'),
  ('pærer', 'pære', 'pærer'),
  ('porre', 'porre', 'porrer'),
  ('porrer', 'porre', 'porrer'),
  ('radise', 'radise', 'radiser'),
  ('radiser', 'radise', 'radiser'),
  ('rødbede', 'rødbede', 'rødbeder'),
  ('rødbeder', 'rødbede', 'rødbeder'),
  ('tomat', 'tomat', 'tomater'),
  ('tomater', 'tomat', 'tomater'),
  ('vindrue', 'vindrue', 'vindruer'),
  ('vindruer', 'vindrue', 'vindruer'),
  ('ært', 'ært', 'ærter'),
  ('ærter', 'ært', 'ærter'),
  ('champignon', 'champignon', 'champignoner'),
  ('champignoner', 'champignon', 'champignoner'),
  ('cherrytomat', 'cherrytomat', 'cherrytomater'),
  ('cherrytomater', 'cherrytomat', 'cherrytomater'),
  ('skoleagurk', 'skoleagurk', 'skoleagurker'),
  ('skoleagurker', 'skoleagurk', 'skoleagurker'),
  ('kotelet', 'kotelet', 'koteletter'),
  ('koteletter', 'kotelet', 'koteletter'),
  ('pølse', 'pølse', 'pølser'),
  ('pølser', 'pølse', 'pølser'),
  ('bøf', 'bøf', 'bøffer'),
  ('bøffer', 'bøf', 'bøffer'),
  ('kyllingebryst', 'kyllingebryst', 'kyllingebryster'),
  ('kyllingebryster', 'kyllingebryst', 'kyllingebryster'),
  ('kylling', 'kylling', 'kyllinger'),
  ('kyllinger', 'kylling', 'kyllinger'),
  ('wrap', 'wrap', 'wraps'),
  ('wraps', 'wrap', 'wraps'),
  ('bolle', 'bolle', 'boller'),
  ('boller', 'bolle', 'boller'),
  ('kage', 'kage', 'kager'),
  ('kager', 'kage', 'kager'),
  ('svamp', 'svamp', 'svampe'),
  ('svampe', 'svamp', 'svampe'),
  ('æble', 'æble', 'æbler'),
  ('æbler', 'æble', 'æbler'),
  ('melon', 'melon', 'meloner'),
  ('meloner', 'melon', 'meloner'),
  ('honningmelon', 'honningmelon', 'honningmeloner'),
  ('honningmeloner', 'honningmelon', 'honningmeloner'),
  ('fennikel', 'fennikel', 'fennikler'),
  ('fennikler', 'fennikel', 'fennikler'),
  ('ost', 'ost', 'oste'),
  ('oste', 'ost', 'oste')
) AS f(key, singular, plural)
WHERE lower(trim(g."name")) = f.key;

UPDATE "generic_ingredients" SET "nameSingular" = "name" WHERE "nameSingular" IS NULL;
UPDATE "generic_ingredients" SET "namePlural" = "name" WHERE "namePlural" IS NULL;
