// GENERATED by scripts/native/sync.mjs from the web app — do not edit by hand.
package dk.packroff.hellocal.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

/** Colours from src/app/globals.css :root (--hf-color-*). */
object HcColors {
    /** --hf-color-page */
    val Page = Color(0xFFFAF8F3)
    /** --hf-color-surface */
    val Surface = Color(0xFFFFFFFF)
    /** --hf-color-card */
    val Card = Color(0xFFEEE9DF)
    /** --hf-color-nav */
    val Nav = Color(0xFFDFD9CC)
    /** --hf-white */
    val White = Color(0xFFFFFFFF)
    /** --hf-color-brand */
    val Brand = Color(0xFF067A46)
    /** --hf-color-brand-dark */
    val BrandDark = Color(0xFF035624)
    /** --hf-color-accent */
    val Accent = Color(0xFFBBF06A)
    /** --hf-color-appbar */
    val Appbar = Color(0xFF067A46)
    /** --hf-color-progress */
    val Progress = Color(0xFF067A46)
    /** --hf-color-progress-dark */
    val ProgressDark = Color(0xFF035624)
    /** --hf-color-selected-bg */
    val SelectedBg = Color(0xFFBBF06A)
    /** --hf-color-selected-border */
    val SelectedBorder = Color(0xFF232323)
    /** --hf-color-selected-text */
    val SelectedText = Color(0xFF232323)
    /** --hf-color-text */
    val Text = Color(0xFF232323)
    /** --hf-color-action */
    val Action = Color(0xFF232323)
    /** --hf-color-action-hover */
    val ActionHover = Color(0xFF353535)
    /** --hf-color-action-active */
    val ActionActive = Color(0xFF4B4B4B)
    /** --hf-color-secondary-hover */
    val SecondaryHover = Color(0xFFE3E3E3)
    /** --hf-color-secondary-active */
    val SecondaryActive = Color(0xFFD2D2D2)
    /** --hf-color-text-secondary */
    val TextSecondary = Color(0xFF656565)
    /** --hf-color-inactive */
    val Inactive = Color(0xFF828282)
    /** --hf-color-placeholder */
    val Placeholder = Color(0xFFC1C0BE)
    /** --hf-color-disabled */
    val Disabled = Color(0xFFA6A29F)
    /** --hf-color-line */
    val Line = Color(0xFFAFADAA)
    /** --hf-color-field-border */
    val FieldBorder = Color(0xFF7D7561)
    /** --hf-color-field-hover */
    val FieldHover = Color(0xFF615C50)
    /** --hf-color-field-focus */
    val FieldFocus = Color(0xFF4A463D)
    /** --hf-color-google */
    val Google = Color(0xFF4285F4)
    /** --hf-color-facebook */
    val Facebook = Color(0xFF00178C)
    /** --hf-color-positive */
    val Positive = Color(0xFFBBF06A)
    /** --hf-color-danger */
    val Danger = Color(0xFFA3271F)
    /** --hf-color-warning */
    val Warning = Color(0xFF8A5A00)
    /** --hf-color-warning-fill */
    val WarningFill = Color(0xFFF2C230)
    /** --hf-color-warning-bg */
    val WarningBg = Color(0xFFFDF3D3)
    /** --hf-color-overlay */
    val Overlay = Color(0x66232323)
    /** --hf-color-watch */
    val Watch = Color(0xFF2F80ED)
    /** --hf-color-faceid */
    val Faceid = Color(0xFF0A7AFF)
    /** --hf-color-faceid-spin */
    val FaceidSpin = Color(0xFF35C4D4)
    /** --mk-color-brand-light */
    val MkBrandLight = Color(0xFF0A8F53)
    /** --hf-color-skeleton */
    val Skeleton = Color(0xFFE2DACB)
    /** --hf-color-skeleton-highlight */
    val SkeletonHighlight = Color(0xFFF2EEE6)
    /** --hf-green */
    val Green = Color(0xFF067A46)
    /** --hf-green-dark */
    val GreenDark = Color(0xFF035624)
    /** --hf-green-light */
    val GreenLight = Color(0xFFBBF06A)
    /** --hf-cream */
    val Cream = Color(0xFFFAF8F3)
    /** --hf-tan */
    val Tan = Color(0xFFEEE9DF)
    /** --hf-tan-dark */
    val TanDark = Color(0xFFDFD9CC)
    /** --hf-black */
    val Black = Color(0xFF232323)
    /** --hf-gray-light */
    val GrayLight = Color(0xFFDFD9CC)
    /** --hf-gray */
    val Gray = Color(0xFF828282)
    /** --hf-gray-dark */
    val GrayDark = Color(0xFF656565)
    /** --hf-red-dark */
    val RedDark = Color(0xFFA3271F)
    /** --hf-green-muted */
    val GreenMuted = Color(0xFF6FA584)
    /** --hf-red-muted */
    val RedMuted = Color(0xFFB98077)
    /** --hf-gray-border */
    val GrayBorder = Color(0xFFAFADAA)
    /** --hf-fab */
    val Fab = Color(0xFF232323)
    /** --hf-lime */
    val Lime = Color(0xFFBBF06A)
    /** --hf-meat */
    val Meat = Color(0xFF8C5A32)
}

/** Spacing, radius and sizes from src/app/globals.css :root. */
object HcDimens {
    /** --hf-space-inline */
    val SpaceInline = 8.dp
    /** --hf-space-block */
    val SpaceBlock = 16.dp
    /** --hf-space-section */
    val SpaceSection = 32.dp
    /** --hf-gutter */
    val Gutter = 16.dp
    /** --hf-radius-card */
    val RadiusCard = 8.dp
    /** --hf-radius-sheet */
    val RadiusSheet = 16.dp
    /** --hf-control-height */
    val ControlHeight = 48.dp
    /** --hf-shell-bar */
    val ShellBar = 56.dp
    /** --hf-shell-sidebar */
    val ShellSidebar = 256.dp
    /** --hf-shell-rail */
    val ShellRail = 64.dp
}

/** Durations from src/app/globals.css :root. */
object HcDurations {
    /** --hf-skeleton-duration */
    const val SkeletonDurationMs = 1400
}

/** One text role per .hf-type-* class in src/app/globals.css. */
class HcTypeRole(val size: Float, val weight: FontWeight, val lineHeight: Float?, val heading: Boolean, val color: Color?)

object HcTypeRoles {
    /** .hf-type-hero */
    val Hero = HcTypeRole(32f, FontWeight(700), 40f, true, null)
    /** .hf-type-page-title */
    val PageTitle = HcTypeRole(22f, FontWeight(700), 28f, true, null)
    /** .hf-type-title */
    val Title = HcTypeRole(17f, FontWeight(700), 22f, true, null)
    /** .hf-type-card-title */
    val CardTitle = HcTypeRole(17f, FontWeight(700), 22f, true, null)
    /** .hf-type-nav-title */
    val NavTitle = HcTypeRole(17f, FontWeight(700), 22f, true, HcColors.White)
    /** .hf-type-body-lg */
    val BodyLg = HcTypeRole(17f, FontWeight(400), 24f, false, null)
    /** .hf-type-button */
    val Button = HcTypeRole(17f, FontWeight(700), 22f, false, null)
    /** .hf-type-input */
    val Input = HcTypeRole(17f, FontWeight(400), 24f, false, null)
    /** .hf-type-body */
    val Body = HcTypeRole(15f, FontWeight(400), 22f, false, null)
    /** .hf-type-section-title */
    val SectionTitle = HcTypeRole(15f, FontWeight(700), 20f, true, null)
    /** .hf-type-small */
    val Small = HcTypeRole(13f, FontWeight(400), 18f, false, null)
    /** .hf-type-caption */
    val Caption = HcTypeRole(13f, FontWeight(400), 18f, false, HcColors.TextSecondary)
    /** .hf-type-label */
    val Label = HcTypeRole(13f, FontWeight(400), 18f, false, null)
    /** .hf-type-progress-active */
    val ProgressActive = HcTypeRole(13f, FontWeight(700), 18f, false, HcColors.ProgressDark)
    /** .hf-type-progress-inactive */
    val ProgressInactive = HcTypeRole(13f, FontWeight(400), 18f, false, HcColors.Inactive)
    /** .hf-type-micro */
    val Micro = HcTypeRole(11f, FontWeight(400), 14f, false, null)
    /** .hf-type-tab */
    val Tab = HcTypeRole(11f, FontWeight(400), 14f, false, null)
}
