-- Alle maaletyper fra smartvaegte/blodtryksapparater (brugerkrav 2026-10-03).
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'FAT_MASS_KG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'FAT_FREE_MASS_KG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'BONE_MASS_KG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'BODY_WATER_KG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'EXTRACELLULAR_WATER_KG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'INTRACELLULAR_WATER_KG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'VISCERAL_FAT_INDEX';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'BASAL_METABOLIC_RATE_KCAL';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'METABOLIC_AGE';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'BLOOD_PRESSURE_SYSTOLIC_MMHG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'BLOOD_PRESSURE_DIASTOLIC_MMHG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'PULSE_WAVE_VELOCITY_M_S';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'VASCULAR_AGE';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'NERVE_HEALTH_SCORE';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'ELECTROCHEMICAL_SKIN_CONDUCTANCE';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'SKIN_TEMPERATURE_C';

-- Version af integrationens datasaet; hoejere version i adapteren = hent historikken igen.
ALTER TABLE "integrations" ADD COLUMN IF NOT EXISTS "fetchVersion" INTEGER NOT NULL DEFAULT 0;
