-- User preference: highlight statistic cards when a validated recommendation
-- engine marks the value as above/below the applicable regional normal range.
ALTER TABLE "users"
ADD COLUMN "warnOnRecommendedLimits" BOOLEAN NOT NULL DEFAULT false;

-- Health sources that can feed the same generic metric store.
ALTER TYPE "HealthMetricSource" ADD VALUE IF NOT EXISTS 'FITBIT';
ALTER TYPE "HealthMetricSource" ADD VALUE IF NOT EXISTS 'WITHINGS';
ALTER TYPE "HealthMetricSource" ADD VALUE IF NOT EXISTS 'GARMIN';

-- Activity / cardiovascular / recovery metrics from Fitbit, HealthKit and
-- Health Connect. Values remain empty until a real integration supplies them.
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'EXERCISE_MINUTES';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'STAND_MINUTES';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'FLOORS_CLIMBED';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'ACTIVE_ZONE_MINUTES';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'RESTING_HEART_RATE_BPM';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'RESTING_HEART_RATE_MINUTES';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'HEART_RATE_MIN_BPM';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'HEART_RATE_MAX_BPM';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'HEART_RATE_VARIABILITY_MS';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'VO2_MAX';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'HEART_RATE_RECOVERY_BPM';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'RESPIRATORY_RATE_BPM';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'OXYGEN_SATURATION_PERCENT';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'TEMPERATURE_C';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'STRESS_SCORE';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'EDA_RESPONSES';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'CARDIO_LOAD';

-- Sleep detail metrics.
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'SLEEP_IN_BED_MINUTES';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'SLEEP_START_MINUTE_OF_DAY';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'SLEEP_END_MINUTE_OF_DAY';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'SLEEP_AWAKE_MINUTES';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'SLEEP_REM_MINUTES';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'SLEEP_LIGHT_MINUTES';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'SLEEP_DEEP_MINUTES';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'SLEEP_SCORE';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'SLEEP_EFFICIENCY_PERCENT';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'SLEEP_AWAKENINGS';

-- Micronutrients, shown with real element symbols (Fe, Ca, K, Na, Mg, …).
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'SODIUM_MG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'MAGNESIUM_MG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'ZINC_MG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'COPPER_MG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'MANGANESE_MG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'SELENIUM_UG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'PHOSPHORUS_MG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'IODINE_UG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'CHROMIUM_UG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'MOLYBDENUM_UG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'VITAMIN_D_UG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'VITAMIN_E_MG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'VITAMIN_K_UG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'VITAMIN_B1_MG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'VITAMIN_B2_MG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'VITAMIN_B3_MG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'VITAMIN_B5_MG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'VITAMIN_B6_MG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'VITAMIN_B7_UG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'VITAMIN_B9_UG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'VITAMIN_B12_UG';
