-- Alle måletyper fra integrationerne (docs/DECISIONS.md 2026-10-03): fedtmasse,
-- fedtfri masse, knoglemasse, visceralt fedt, blodtryk, karstivhed, EKG m.m.
-- Håndskrevet (ingen lokal PostgreSQL).

ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'FAT_MASS_KG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'FAT_FREE_MASS_KG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'SKELETAL_MUSCLE_MASS_KG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'BONE_MASS_KG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'EXTRACELLULAR_WATER_KG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'INTRACELLULAR_WATER_KG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'VISCERAL_FAT_INDEX';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'PROTEIN_PERCENT';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'BASAL_METABOLIC_RATE_KCAL';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'METABOLIC_AGE_YEARS';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'BLOOD_PRESSURE_SYSTOLIC_MMHG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'BLOOD_PRESSURE_DIASTOLIC_MMHG';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'PULSE_WAVE_VELOCITY_M_S';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'VASCULAR_AGE_YEARS';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'QRS_INTERVAL_MS';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'PR_INTERVAL_MS';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'QT_INTERVAL_MS';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'QTC_INTERVAL_MS';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'FITNESS_AGE_YEARS';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'SKIN_TEMPERATURE_C';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'BLOOD_GLUCOSE_MMOL_L';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'NERVE_HEALTH_SCORE';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'SKIN_CONDUCTANCE_US';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'RECOVERY_SCORE';
ALTER TYPE "HealthMetricType" ADD VALUE IF NOT EXISTS 'STRAIN_SCORE';
