#!/usr/bin/env node
// Generates the native design tokens and texts from the web app, so the
// Android/iPhone app and widgets can never drift from the web design:
//
//   src/app/globals.css (:root tokens + .hf-type-* roles)
//     → native/shared/.../theme/HcTokens.kt          (app screens, Android + iPhone)
//     → native/android/widgets/.../HcTokens.kt        (Android widgets)
//     → native/androidApp/src/main/res/values/hc_tokens.xml
//     → native/ios/HelloCalWidgets/HcTokens.swift     (iPhone widgets)
//   src/i18n/locales/*.json
//     → native/shared/src/commonMain/composeResources/files/locales/*.json
//   src/lib/{food-latin,knowledge,knowledge-research,micronutrient-info,toxins}.ts
//     → native/shared/.../screens/onboarding/OnbKnowledgeData.kt
//     → native/shared/.../screens/food/FoodReferenceData.kt
//
//   node scripts/native/sync.mjs          write the generated files
//   node scripts/native/sync.mjs --check  exit 1 if any generated file is stale
//
// Needs Node >= 22.13 (node:module stripTypeScriptTypes) — no npm packages.
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const CHECK = process.argv.includes("--check");
const HEADER = "GENERATED by scripts/native/sync.mjs from the web app — do not edit by hand.";

const css = readFileSync(join(ROOT, "src/app/globals.css"), "utf8");

// ---- :root custom properties -------------------------------------------
const rootBlock = css.match(/:root\s*\{([\s\S]*?)\n\}/)?.[1] ?? "";
const vars = {};
for (const m of rootBlock.replace(/\/\*[\s\S]*?\*\//g, "").matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);/g)) vars[m[1]] = m[2].trim();

function resolveVar(value, depth = 0) {
  if (depth > 10) throw new Error(`var() cycle at ${value}`);
  const m = value.match(/^var\(\s*(--[a-z0-9-]+)\s*(?:,\s*([^)]+))?\)$/);
  if (!m) return value;
  if (vars[m[1]] !== undefined) return resolveVar(vars[m[1]], depth + 1);
  if (m[2]) return m[2].trim();
  throw new Error(`Unknown token ${m[1]}`);
}

/** CSS colour → ARGB hex "FFRRGGBB", or null if the value isn't a colour. */
function argb(value) {
  const v = value.trim().toLowerCase();
  let m = v.match(/^#([0-9a-f]{3}|[0-9a-f]{6}|[0-9a-f]{8})$/);
  if (m) {
    let h = m[1];
    if (h.length === 3) h = [...h].map((c) => c + c).join("");
    if (h.length === 6) h += "ff";
    return (h.slice(6, 8) + h.slice(0, 6)).toUpperCase();
  }
  m = v.match(/^rgba?\(\s*(\d+)[\s,]+(\d+)[\s,]+(\d+)\s*(?:[/,]\s*([\d.]+)(%?))?\s*\)$/);
  if (m) {
    const a = m[4] === undefined ? 1 : m[5] ? Number(m[4]) / 100 : Number(m[4]);
    const hex = (n) => Math.round(n).toString(16).padStart(2, "0");
    return (hex(a * 255) + hex(+m[1]) + hex(+m[2]) + hex(+m[3])).toUpperCase();
  }
  return null;
}

const pascal = (s) => s.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const camel = (s) => {
  const p = pascal(s);
  return p[0].toLowerCase() + p.slice(1);
};

const colors = [];
const dimensions = [];
const durations = [];
for (const name of Object.keys(vars)) {
  if (!name.startsWith("--hf-") && !name.startsWith("--mk-")) continue;
  const resolved = resolveVar(vars[name]);
  const color = argb(resolved);
  const key = name.replace(/^--(hf|mk)-(color-)?/, (_, p) => (p === "mk" ? "mk-" : ""));
  if (color) colors.push({ name, key, argb: color });
  else if (/^-?\d+(\.\d+)?px$/.test(resolved)) dimensions.push({ name, key, px: parseFloat(resolved) });
  else if (/^\d+ms$/.test(resolved)) durations.push({ name, key, ms: parseInt(resolved, 10) });
}
// Same colour under legacy aliases is fine; same Kotlin name is not.
const uniq = (list) => [...new Map(list.map((x) => [x.key, x])).values()];

// ---- typography roles (.hf-type-*) -------------------------------------
const typeRoles = [];
for (const m of css.matchAll(/((?:\.hf-type-[a-z0-9-]+\s*,\s*)*\.hf-type-[a-z0-9-]+)\s*\{([^}]*)\}/g)) {
  const body = m[2];
  const size = body.match(/font-size:\s*(\d+)px/)?.[1];
  if (!size) continue;
  const weight = body.match(/font-weight:\s*(\d+)/)?.[1] ?? "400";
  const lineHeight = body.match(/line-height:\s*(\d+)px/)?.[1];
  const family = /font-hf-heading/.test(body) ? "Heading" : "Body";
  const colorVar = body.match(/(?:^|[;\s])color:\s*(var\([^)]*\))/)?.[1];
  const color = colorVar ? colors.find((c) => c.name === colorVar.match(/var\(\s*(--[a-z0-9-]+)/)[1]) ?? null : null;
  for (const sel of m[1].split(",").map((s) => s.trim())) {
    if (/::|:/.test(sel.replace(/^\.hf-type-/, ""))) continue;
    const key = sel.replace(/^\.hf-type-/, "");
    if (typeRoles.some((r) => r.key === key)) continue;
    typeRoles.push({ key, size: +size, weight: +weight, lineHeight: lineHeight ? +lineHeight : null, family, color });
  }
}

const colorList = uniq(colors);
const dimList = uniq(dimensions);
const typeList = typeRoles;

// ---- writers --------------------------------------------------------------
function kotlinTokens(pkg, { withTypography }) {
  const lines = [
    `// ${HEADER}`,
    `package ${pkg}`,
    "",
    "import androidx.compose.ui.graphics.Color",
    ...(withTypography ? ["import androidx.compose.ui.text.font.FontWeight", "import androidx.compose.ui.unit.dp"] : []),
    "",
    "/** Colours from src/app/globals.css :root (--hf-color-*). */",
    "object HcColors {",
    ...colorList.map((c) => `    /** ${c.name} */\n    val ${pascal(c.key)} = Color(0x${c.argb})`),
    "}",
  ];
  if (withTypography) {
    lines.push(
      "",
      "/** Spacing, radius and sizes from src/app/globals.css :root. */",
      "object HcDimens {",
      ...dimList.map((d) => `    /** ${d.name} */\n    val ${pascal(d.key)} = ${d.px}.dp`),
      "}",
      "",
      "/** Durations from src/app/globals.css :root. */",
      "object HcDurations {",
      ...durations.map((d) => `    /** ${d.name} */\n    const val ${pascal(d.key)}Ms = ${d.ms}`),
      "}",
      "",
      "/** One text role per .hf-type-* class in src/app/globals.css. */",
      "class HcTypeRole(val size: Float, val weight: FontWeight, val lineHeight: Float?, val heading: Boolean, val color: Color?)",
      "",
      "object HcTypeRoles {",
      ...typeList.map(
        (t) =>
          `    /** .hf-type-${t.key} */\n    val ${pascal(t.key)} = HcTypeRole(${t.size}f, FontWeight(${t.weight}), ${t.lineHeight === null ? "null" : `${t.lineHeight}f`}, ${t.family === "Heading"}, ${t.color ? `HcColors.${pascal(t.color.key)}` : "null"})`,
      ),
      "}",
    );
  }
  return lines.join("\n") + "\n";
}

function swiftTokens() {
  return [
    `// ${HEADER}`,
    "import SwiftUI",
    "",
    "/// Colours from src/app/globals.css :root (--hf-color-*).",
    "enum HcColors {",
    ...colorList.map((c) => {
      const a = parseInt(c.argb.slice(0, 2), 16) / 255;
      const [r, g, b] = [2, 4, 6].map((i) => parseInt(c.argb.slice(i, i + 2), 16) / 255);
      return `    /// ${c.name}\n    static let ${camel(c.key)} = Color(.sRGB, red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)}, opacity: ${a.toFixed(4)})`;
    }),
    "}",
    "",
    "/// Text roles (.hf-type-*): size, weight, line height.",
    "enum HcType {",
    ...typeList.map((t) => {
      const w = { 400: ".regular", 500: ".medium", 600: ".semibold", 700: ".bold", 800: ".heavy" }[t.weight] ?? ".regular";
      return `    /// .hf-type-${t.key}\n    static let ${camel(t.key)} = Font.system(size: ${t.size}, weight: ${w})`;
    }),
    "}",
    "",
  ].join("\n");
}

function androidXml() {
  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    `<!-- ${HEADER} -->`,
    "<resources>",
    ...colorList.map((c) => `    <color name="hc_${c.key.replace(/-/g, "_")}">#${c.argb}</color>`),
    ...dimList.map((d) => `    <dimen name="hc_${d.key.replace(/-/g, "_")}">${d.px}dp</dimen>`),
    "</resources>",
    "",
  ].join("\n");
}

const outputs = new Map();
outputs.set("native/shared/src/commonMain/kotlin/dk/packroff/hellocal/theme/HcTokens.kt", kotlinTokens("dk.packroff.hellocal.theme", { withTypography: true }));
outputs.set("native/android/widgets/src/main/java/dk/packroff/hellocal/widgets/HcTokens.kt", kotlinTokens("dk.packroff.hellocal.widgets", { withTypography: false }));
outputs.set("native/androidApp/src/main/res/values/hc_tokens.xml", androidXml());
outputs.set("native/ios/HelloCalWidgets/HcTokens.swift", swiftTokens());

const LOCALES = join(ROOT, "src/i18n/locales");
for (const file of readdirSync(LOCALES).filter((f) => f.endsWith(".json")).sort()) {
  // Re-serialised compactly; same keys and values as the web dictionaries.
  const json = JSON.stringify(JSON.parse(readFileSync(join(LOCALES, file), "utf8")));
  outputs.set(`native/shared/src/commonMain/composeResources/files/locales/${file}`, `${json}\n`);
}

// ---- icons: every Tabler icon the (non-admin) web app imports -------------
function walkFiles(dir, out = []) {
  for (const name of readdirSync(join(ROOT, dir), { withFileTypes: true })) {
    const rel = `${dir}/${name.name}`;
    if (name.isDirectory()) {
      if (!/\/(admin|api)$/.test(rel)) walkFiles(rel, out);
    } else if (/\.(tsx|ts)$/.test(name.name)) out.push(rel);
  }
  return out;
}
const iconNames = new Set();
for (const file of walkFiles("src")) {
  const source = readFileSync(join(ROOT, file), "utf8");
  for (const m of source.matchAll(/import\s*\{([^}]*)\}\s*from\s*["']@tabler\/icons-react["']/g)) {
    for (const part of m[1].split(",")) {
      const name = part.trim().split(/\s+as\s+/)[0].trim();
      if (/^Icon[A-Z0-9]\w*$/.test(name)) iconNames.add(name);
    }
  }
}
const TABLER = [join(ROOT, "node_modules/@tabler/icons-react/dist/esm/icons")];
const toPath = (tag, a) => {
  const n = (k) => Number(a[k] ?? 0);
  switch (tag) {
    case "path":
      return a.d;
    case "line":
      return `M${n("x1")} ${n("y1")}L${n("x2")} ${n("y2")}`;
    case "polyline":
    case "polygon": {
      const pts = a.points.trim().split(/[\s,]+/).map(Number);
      let d = `M${pts[0]} ${pts[1]}`;
      for (let i = 2; i < pts.length; i += 2) d += `L${pts[i]} ${pts[i + 1]}`;
      return tag === "polygon" ? `${d}Z` : d;
    }
    case "circle":
    case "ellipse": {
      const cx = n("cx");
      const cy = n("cy");
      const rx = tag === "circle" ? n("r") : n("rx");
      const ry = tag === "circle" ? n("r") : n("ry");
      return `M${cx - rx} ${cy}a${rx} ${ry} 0 1 0 ${2 * rx} 0a${rx} ${ry} 0 1 0 ${-2 * rx} 0`;
    }
    case "rect": {
      const x = n("x");
      const y = n("y");
      const w = n("width");
      const h = n("height");
      const r = Math.min(Number(a.rx ?? a.ry ?? 0), w / 2, h / 2);
      if (!r) return `M${x} ${y}h${w}v${h}h${-w}Z`;
      return `M${x + r} ${y}h${w - 2 * r}a${r} ${r} 0 0 1 ${r} ${r}v${h - 2 * r}a${r} ${r} 0 0 1 ${-r} ${r}h${-(w - 2 * r)}a${r} ${r} 0 0 1 ${-r} ${-r}v${-(h - 2 * r)}a${r} ${r} 0 0 1 ${r} ${-r}Z`;
    }
    default:
      return null;
  }
};
const iconEntries = [];
if (existsSync(TABLER[0])) {
  for (const name of [...iconNames].sort()) {
    const file = join(TABLER[0], `${name}.mjs`);
    if (!existsSync(file)) continue;
    const src = readFileSync(file, "utf8");
    const nodes = JSON.parse(src.match(/const __iconNode = (\[[\s\S]*?\]);\n/)[1]);
    const filled = /createReactComponent\("filled"/.test(src);
    const paths = nodes.map(([tag, attrs]) => toPath(tag, attrs)).filter(Boolean);
    iconEntries.push({ name: name.replace(/^Icon/, ""), filled, paths });
  }
  const kt = [
    `// ${HEADER}`,
    "// Tabler icons (MIT) used by the web app — same artwork on Android and iPhone.",
    "package dk.packroff.hellocal.ui.icons",
    "",
    "internal object TablerData {",
    "    /** name → (filled, SVG path data on a 24×24 grid) */",
    "    val icons: Map<String, Pair<Boolean, List<String>>> = mapOf(",
    ...iconEntries.map((e) => `        ${JSON.stringify(e.name)} to (${e.filled} to listOf(${e.paths.map((p) => JSON.stringify(p).replace(/\$/g, "\\$")).join(", ")})),`),
    "    )",
    "}",
    "",
  ].join("\n");
  outputs.set("native/shared/src/commonMain/kotlin/dk/packroff/hellocal/ui/icons/TablerData.kt", kt);
}

// ---- static reference data: src/lib/*.ts → Kotlin -------------------------
/** Imports src/lib/<name>.ts (plus the @/lib modules it imports) with no npm
 * package: Node's own stripTypeScriptTypes removes the types, the result is
 * written as .mjs to a temp dir and imported. */
async function importLib(names) {
  const { stripTypeScriptTypes } = await import("node:module");
  if (typeof stripTypeScriptTypes !== "function") {
    throw new Error(`node:module stripTypeScriptTypes mangler — scripts/native/sync.mjs kræver Node >= 22.13 (kører ${process.version}).`);
  }
  const emit = process.emitWarning;
  process.emitWarning = (warning, ...rest) => {
    const type = typeof rest[0] === "string" ? rest[0] : rest[0]?.type;
    if (type === "ExperimentalWarning" || warning?.name === "ExperimentalWarning") return;
    emit.call(process, warning, ...rest);
  };
  const dir = mkdtempSync(join(tmpdir(), "hellocal-sync-"));
  try {
    const queue = [...names];
    const done = new Set();
    while (queue.length) {
      const name = queue.shift();
      if (done.has(name)) continue;
      done.add(name);
      const js = stripTypeScriptTypes(readFileSync(join(ROOT, "src/lib", `${name}.ts`), "utf8")).replace(
        /(from\s*["'])@\/lib\/([\w-]+)(["'])/g,
        (_, before, dep, after) => {
          queue.push(dep);
          return `${before}./${dep}.mjs${after}`;
        },
      );
      writeFileSync(join(dir, `${name}.mjs`), js);
    }
    const modules = {};
    for (const name of names) modules[name] = await import(pathToFileURL(join(dir, `${name}.mjs`)).href);
    return modules;
  } finally {
    process.emitWarning = emit;
    rmSync(dir, { recursive: true, force: true });
  }
}

/** Kotlin string literal (handles quotes, backslashes, $, newlines). */
function kstr(value) {
  if (typeof value !== "string") throw new Error(`Forventede tekst, fik ${JSON.stringify(value)}`);
  const esc = { "\\": "\\\\", '"': '\\"', $: "\\$", "\n": "\\n", "\r": "\\r", "\t": "\\t" };
  return `"${[...value].map((c) => esc[c] ?? (c.codePointAt(0) < 0x20 ? `\\u${c.codePointAt(0).toString(16).padStart(4, "0")}` : c)).join("")}"`;
}
const kopt = (value) => (value == null ? "null" : kstr(value));
const klist = (items, render = kstr) => (items?.length ? `listOf(${items.map(render).join(", ")})` : "emptyList()");

/** Fails loudly when the web adds a field the native data classes don't carry yet. */
function checkKeys(obj, allowed, where) {
  const extra = Object.keys(obj).filter((k) => !allowed.includes(k));
  if (extra.length) throw new Error(`${where}: nye felter ${extra.join(", ")} — tilføj dem i scripts/native/sync.mjs og Kotlin-klassen.`);
}

/** `internal object <name> { val all … }` split into part functions of 8, so no
 * single JVM method gets near the 64 KB limit. */
function chunkedObject(name, type, items, render) {
  const parts = [];
  for (let i = 0; i < items.length; i += 8) parts.push(items.slice(i, i + 8));
  return [
    `internal object ${name} {`,
    `    val all: List<${type}> by lazy { ${parts.map((_, i) => `part${i}()`).join(" + ") || "emptyList()"} }`,
    ...parts.flatMap((part, i) => ["", `    private fun part${i}(): List<${type}> = listOf(`, ...part.map((x) => `        ${render(x)},`), "    )"]),
    "}",
  ];
}

const lib = await importLib(["food-latin", "knowledge", "micronutrient-info", "toxins"]);
const FOOD_TERMS = lib["food-latin"].FOOD_TERMS;
const KNOWLEDGE_ARTICLES = lib.knowledge.KNOWLEDGE_ARTICLES;
const MICRONUTRIENT_INFO = lib["micronutrient-info"].MICRONUTRIENT_INFO;
const TOXINS = lib.toxins.TOXINS;

const MICRO_KEYS = ["key", "group", "name", "alsoKnownAs", "function", "sources", "referenceIntake", "tooLittleOrMuch", "searchTerm"];
for (const m of MICRONUTRIENT_INFO) checkKeys(m, MICRO_KEYS, `MICRONUTRIENT_INFO ${m.key}`);

const onbLink = (s) => {
  checkKeys(s, ["label", "href"], `kilde ${s.label}`);
  return `OnbSourceLink(${kstr(s.label)}, ${kstr(s.href)})`;
};

const onbKt = [
  `// ${HEADER}`,
  "// Source: src/lib/food-latin.ts, src/lib/knowledge.ts, src/lib/knowledge-research.ts,",
  "// src/lib/micronutrient-info.ts (static web data, no API).",
  "package dk.packroff.hellocal.screens.onboarding",
  "",
  "internal data class OnbSourceLink(val label: String, val href: String)",
  "",
  "internal data class FoodTerm(",
  "    val term: String,",
  "    val aliases: List<String>,",
  "    val danish: String,",
  "    val explanation: String,",
  "    val source: OnbSourceLink,",
  ")",
  "",
  "internal data class KnowledgeArticle(",
  "    val slug: String,",
  "    val category: String,",
  "    val title: String,",
  "    val summary: String,",
  "    val body: List<String>,",
  "    val funFact: String?,",
  "    val source: OnbSourceLink,",
  "    val moreSources: List<OnbSourceLink>,",
  ")",
  "",
  "internal data class MicronutrientInfo(",
  ...MICRO_KEYS.map((k) => `    val ${k}: String,`),
  ")",
  "",
  ...chunkedObject("FoodTerms", "FoodTerm", FOOD_TERMS, (t) => {
    checkKeys(t, ["term", "aliases", "danish", "explanation", "source"], `FOOD_TERMS ${t.term}`);
    return `FoodTerm(${kstr(t.term)}, ${klist(t.aliases)}, ${kstr(t.danish)}, ${kstr(t.explanation)}, ${onbLink(t.source)})`;
  }),
  "",
  ...chunkedObject("KnowledgeArticles", "KnowledgeArticle", KNOWLEDGE_ARTICLES, (a) => {
    checkKeys(a, ["slug", "category", "title", "summary", "body", "funFact", "source", "moreSources"], `KNOWLEDGE_ARTICLES ${a.slug}`);
    return `KnowledgeArticle(${kstr(a.slug)}, ${kstr(a.category)}, ${kstr(a.title)}, ${kstr(a.summary)}, ${klist(a.body)}, ${kopt(a.funFact)}, ${onbLink(a.source)}, ${klist(a.moreSources, onbLink)})`;
  }),
  "",
  ...chunkedObject("Micronutrients", "MicronutrientInfo", MICRONUTRIENT_INFO, (m) => `MicronutrientInfo(${MICRO_KEYS.map((k) => kstr(m[k])).join(", ")})`),
  "",
].join("\n");
outputs.set("native/shared/src/commonMain/kotlin/dk/packroff/hellocal/screens/onboarding/OnbKnowledgeData.kt", onbKt);

// Lowercase name or alias → term, built exactly like LOOKUP in src/lib/food-latin.ts.
const foodTermLookup = new Map();
for (const t of FOOD_TERMS) for (const n of [t.term, ...(t.aliases ?? [])]) foodTermLookup.set(n.toLowerCase(), t.term);

const foodKt = [
  `// ${HEADER}`,
  "// Source: src/lib/toxins.ts, src/lib/micronutrient-info.ts and src/lib/food-latin.ts — same Danish texts as the web.",
  "package dk.packroff.hellocal.screens.food",
  "",
  "data class ToxinLink(val label: String, val url: String)",
  "",
  "data class ToxinInfo(",
  "    val key: String,",
  "    val name: String,",
  "    val foods: String,",
  "    val description: String,",
  "    val advice: String,",
  "    val pregnancy: String?,",
  "    val fertility: String?,",
  "    val links: List<ToxinLink>,",
  "    val terms: List<String>,",
  "    val excludeIf: List<String> = emptyList(),",
  ")",
  "",
  "data class MicronutrientInfo(",
  ...MICRO_KEYS.map((k) => `    val ${k}: String,`),
  ")",
  "",
  "object FoodReferenceData {",
  "    val toxins: List<ToxinInfo> = listOf(",
  ...TOXINS.flatMap((t) => {
    checkKeys(t, ["key", "name", "foods", "description", "advice", "pregnancy", "fertility", "links", "terms", "excludeIf"], `TOXINS ${t.key}`);
    const link = (l) => {
      checkKeys(l, ["label", "url"], `TOXINS ${t.key} link`);
      return `ToxinLink(${kstr(l.label)}, ${kstr(l.url)})`;
    };
    return [
      "        ToxinInfo(",
      `            key = ${kstr(t.key)},`,
      `            name = ${kstr(t.name)},`,
      `            foods = ${kstr(t.foods)},`,
      `            description = ${kstr(t.description)},`,
      `            advice = ${kstr(t.advice)},`,
      `            pregnancy = ${kopt(t.pregnancy)},`,
      `            fertility = ${kopt(t.fertility)},`,
      `            links = ${klist(t.links, link)},`,
      `            terms = ${klist(t.terms)},`,
      `            excludeIf = ${klist(t.excludeIf)},`,
      "        ),",
    ];
  }),
  "    )",
  "",
  "    val micronutrients: List<MicronutrientInfo> = listOf(",
  ...MICRONUTRIENT_INFO.flatMap((m) => ["        MicronutrientInfo(", ...MICRO_KEYS.map((k) => `            ${k} = ${kstr(m[k])},`), "        ),"]),
  "    )",
  "",
  "    /** src/lib/food-latin.ts FOOD_TERMS: lowercase name or alias -> term (linked in ingredient lists). */",
  "    val foodTermLookup: Map<String, String> = mapOf(",
  ...[...foodTermLookup].map(([name, term]) => `        ${kstr(name)} to ${kstr(term)},`),
  "    )",
  "",
  "    val micronutrientByKey: Map<String, MicronutrientInfo> = micronutrients.associateBy { it.key }",
  "}",
  "",
].join("\n");
outputs.set("native/shared/src/commonMain/kotlin/dk/packroff/hellocal/screens/food/FoodReferenceData.kt", foodKt);

// ---- binary assets copied 1:1 (app icon) ---------------------------------
const binaries = new Map([["native/androidApp/src/main/res/mipmap-xxxhdpi/ic_launcher.png", "src/app/icon.png"]]);

let stale = [];
for (const [rel, srcRel] of binaries) {
  const abs = join(ROOT, rel);
  const want = readFileSync(join(ROOT, srcRel));
  if (existsSync(abs) && Buffer.compare(readFileSync(abs), want) === 0) continue;
  stale.push(rel);
  if (!CHECK) {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, want);
  }
}
for (const [rel, content] of outputs) {
  const abs = join(ROOT, rel);
  const current = existsSync(abs) ? readFileSync(abs, "utf8").replace(/\r\n/g, "\n") : null;
  if (current === content) continue;
  stale.push(rel);
  if (!CHECK) {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
  }
}

if (CHECK) {
  if (stale.length) {
    console.error(`Native-filer er ikke i takt med web — kør: node scripts/native/sync.mjs\n${stale.map((s) => `  ${s}`).join("\n")}`);
    process.exit(1);
  }
  console.log("Native farver/typografi/tekster/ikoner/videnstekster er i takt med web.");
} else {
  console.log(stale.length ? `Opdaterede ${stale.length} filer:\n${stale.map((s) => `  ${s}`).join("\n")}` : "Alt var allerede i takt.");
  console.log(`${colorList.length} farver, ${dimList.length} mål, ${typeList.length} tekstroller, ${[...outputs.keys()].filter((k) => k.includes("/locales/")).length} sprog, ${iconEntries.length} ikoner, ${FOOD_TERMS.length} latinske madord, ${KNOWLEDGE_ARTICLES.length} artikler, ${MICRONUTRIENT_INFO.length} vitaminer/mineraler, ${TOXINS.length} toksiner.`);
}
