#!/usr/bin/env node
// Generates the native design tokens and texts from the web app, so the
// Android/iPhone app and widgets can never drift from the web design:
//
//   src/app/globals.css (:root tokens + .hf-type-* roles)
//     → native/shared/.../theme/HcTokens.kt          (app screens, Android + iPhone)
//     → native/android/widgets/.../HcTokens.kt        (Android widgets)
//     → native/androidApp/src/main/res/values/hc_tokens.xml
//     → native/ios/HelloCalWidgets/HcTokens.swift     (iPhone widgets)
//   src/i18n/locales/*.json
//     → native/shared/src/commonMain/composeResources/files/locales/*.json
//
//   node scripts/native/sync.mjs          write the generated files
//   node scripts/native/sync.mjs --check  exit 1 if any generated file is stale
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const CHECK = process.argv.includes("--check");
const HEADER = "GENERATED by scripts/native/sync.mjs from the web app — do not edit by hand.";

const css = readFileSync(join(ROOT, "src/app/globals.css"), "utf8");

// ---- :root custom properties -------------------------------------------
const rootBlock = css.match(/:root\s*\{([\s\S]*?)\n\}/)?.[1] ?? "";
const vars = {};
for (const m of rootBlock.replace(/\/\*[\s\S]*?\*\//g, "").matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);/g)) vars[m[1]] = m[2].trim();

function resolveVar(value, depth = 0) {
  if (depth > 10) throw new Error(`var() cycle at ${value}`);
  const m = value.match(/^var\(\s*(--[a-z0-9-]+)\s*(?:,\s*([^)]+))?\)$/);
  if (!m) return value;
  if (vars[m[1]] !== undefined) return resolveVar(vars[m[1]], depth + 1);
  if (m[2]) return m[2].trim();
  throw new Error(`Unknown token ${m[1]}`);
}

/** CSS colour → ARGB hex "FFRRGGBB", or null if the value isn't a colour. */
function argb(value) {
  const v = value.trim().toLowerCase();
  let m = v.match(/^#([0-9a-f]{3}|[0-9a-f]{6}|[0-9a-f]{8})$/);
  if (m) {
    let h = m[1];
    if (h.length === 3) h = [...h].map((c) => c + c).join("");
    if (h.length === 6) h += "ff";
    return (h.slice(6, 8) + h.slice(0, 6)).toUpperCase();
  }
  m = v.match(/^rgba?\(\s*(\d+)[\s,]+(\d+)[\s,]+(\d+)\s*(?:[/,]\s*([\d.]+)(%?))?\s*\)$/);
  if (m) {
    const a = m[4] === undefined ? 1 : m[5] ? Number(m[4]) / 100 : Number(m[4]);
    const hex = (n) => Math.round(n).toString(16).padStart(2, "0");
    return (hex(a * 255) + hex(+m[1]) + hex(+m[2]) + hex(+m[3])).toUpperCase();
  }
  return null;
}

const pascal = (s) => s.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const camel = (s) => {
  const p = pascal(s);
  return p[0].toLowerCase() + p.slice(1);
};

const colors = [];
const dimensions = [];
const durations = [];
for (const name of Object.keys(vars)) {
  if (!name.startsWith("--hf-") && !name.startsWith("--mk-")) continue;
  const resolved = resolveVar(vars[name]);
  const color = argb(resolved);
  const key = name.replace(/^--(hf|mk)-(color-)?/, (_, p) => (p === "mk" ? "mk-" : ""));
  if (color) colors.push({ name, key, argb: color });
  else if (/^-?\d+(\.\d+)?px$/.test(resolved)) dimensions.push({ name, key, px: parseFloat(resolved) });
  else if (/^\d+ms$/.test(resolved)) durations.push({ name, key, ms: parseInt(resolved, 10) });
}
// Same colour under legacy aliases is fine; same Kotlin name is not.
const uniq = (list) => [...new Map(list.map((x) => [x.key, x])).values()];

// ---- typography roles (.hf-type-*) -------------------------------------
const typeRoles = [];
for (const m of css.matchAll(/((?:\.hf-type-[a-z0-9-]+\s*,\s*)*\.hf-type-[a-z0-9-]+)\s*\{([^}]*)\}/g)) {
  const body = m[2];
  const size = body.match(/font-size:\s*(\d+)px/)?.[1];
  if (!size) continue;
  const weight = body.match(/font-weight:\s*(\d+)/)?.[1] ?? "400";
  const lineHeight = body.match(/line-height:\s*(\d+)px/)?.[1];
  const family = /font-hf-heading/.test(body) ? "Heading" : "Body";
  const colorVar = body.match(/(?:^|[;\s])color:\s*(var\([^)]*\))/)?.[1];
  const color = colorVar ? colors.find((c) => c.name === colorVar.match(/var\(\s*(--[a-z0-9-]+)/)[1]) ?? null : null;
  for (const sel of m[1].split(",").map((s) => s.trim())) {
    if (/::|:/.test(sel.replace(/^\.hf-type-/, ""))) continue;
    const key = sel.replace(/^\.hf-type-/, "");
    if (typeRoles.some((r) => r.key === key)) continue;
    typeRoles.push({ key, size: +size, weight: +weight, lineHeight: lineHeight ? +lineHeight : null, family, color });
  }
}

const colorList = uniq(colors);
const dimList = uniq(dimensions);
const typeList = typeRoles;

// ---- writers --------------------------------------------------------------
function kotlinTokens(pkg, { withTypography }) {
  const lines = [
    `// ${HEADER}`,
    `package ${pkg}`,
    "",
    "import androidx.compose.ui.graphics.Color",
    ...(withTypography ? ["import androidx.compose.ui.text.font.FontWeight", "import androidx.compose.ui.unit.dp"] : []),
    "",
    "/** Colours from src/app/globals.css :root (--hf-color-*). */",
    "object HcColors {",
    ...colorList.map((c) => `    /** ${c.name} */\n    val ${pascal(c.key)} = Color(0x${c.argb})`),
    "}",
  ];
  if (withTypography) {
    lines.push(
      "",
      "/** Spacing, radius and sizes from src/app/globals.css :root. */",
      "object HcDimens {",
      ...dimList.map((d) => `    /** ${d.name} */\n    val ${pascal(d.key)} = ${d.px}.dp`),
      "}",
      "",
      "/** Durations from src/app/globals.css :root. */",
      "object HcDurations {",
      ...durations.map((d) => `    /** ${d.name} */\n    const val ${pascal(d.key)}Ms = ${d.ms}`),
      "}",
      "",
      "/** One text role per .hf-type-* class in src/app/globals.css. */",
      "class HcTypeRole(val size: Float, val weight: FontWeight, val lineHeight: Float?, val heading: Boolean, val color: Color?)",
      "",
      "object HcTypeRoles {",
      ...typeList.map(
        (t) =>
          `    /** .hf-type-${t.key} */\n    val ${pascal(t.key)} = HcTypeRole(${t.size}f, FontWeight(${t.weight}), ${t.lineHeight === null ? "null" : `${t.lineHeight}f`}, ${t.family === "Heading"}, ${t.color ? `HcColors.${pascal(t.color.key)}` : "null"})`,
      ),
      "}",
    );
  }
  return lines.join("\n") + "\n";
}

function swiftTokens() {
  return [
    `// ${HEADER}`,
    "import SwiftUI",
    "",
    "/// Colours from src/app/globals.css :root (--hf-color-*).",
    "enum HcColors {",
    ...colorList.map((c) => {
      const a = parseInt(c.argb.slice(0, 2), 16) / 255;
      const [r, g, b] = [2, 4, 6].map((i) => parseInt(c.argb.slice(i, i + 2), 16) / 255);
      return `    /// ${c.name}\n    static let ${camel(c.key)} = Color(.sRGB, red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)}, opacity: ${a.toFixed(4)})`;
    }),
    "}",
    "",
    "/// Text roles (.hf-type-*): size, weight, line height.",
    "enum HcType {",
    ...typeList.map((t) => {
      const w = { 400: ".regular", 500: ".medium", 600: ".semibold", 700: ".bold", 800: ".heavy" }[t.weight] ?? ".regular";
      return `    /// .hf-type-${t.key}\n    static let ${camel(t.key)} = Font.system(size: ${t.size}, weight: ${w})`;
    }),
    "}",
    "",
  ].join("\n");
}

function androidXml() {
  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    `<!-- ${HEADER} -->`,
    "<resources>",
    ...colorList.map((c) => `    <color name="hc_${c.key.replace(/-/g, "_")}">#${c.argb}</color>`),
    ...dimList.map((d) => `    <dimen name="hc_${d.key.replace(/-/g, "_")}">${d.px}dp</dimen>`),
    "</resources>",
    "",
  ].join("\n");
}

const outputs = new Map();
outputs.set("native/shared/src/commonMain/kotlin/dk/packroff/hellocal/theme/HcTokens.kt", kotlinTokens("dk.packroff.hellocal.theme", { withTypography: true }));
outputs.set("native/android/widgets/src/main/java/dk/packroff/hellocal/widgets/HcTokens.kt", kotlinTokens("dk.packroff.hellocal.widgets", { withTypography: false }));
outputs.set("native/androidApp/src/main/res/values/hc_tokens.xml", androidXml());
outputs.set("native/ios/HelloCalWidgets/HcTokens.swift", swiftTokens());

const LOCALES = join(ROOT, "src/i18n/locales");
for (const file of readdirSync(LOCALES).filter((f) => f.endsWith(".json")).sort()) {
  // Re-serialised compactly; same keys and values as the web dictionaries.
  const json = JSON.stringify(JSON.parse(readFileSync(join(LOCALES, file), "utf8")));
  outputs.set(`native/shared/src/commonMain/composeResources/files/locales/${file}`, `${json}\n`);
}

// ---- icons: every Tabler icon the (non-admin) web app imports -------------
function walkFiles(dir, out = []) {
  for (const name of readdirSync(join(ROOT, dir), { withFileTypes: true })) {
    const rel = `${dir}/${name.name}`;
    if (name.isDirectory()) {
      if (!/\/(admin|api)$/.test(rel)) walkFiles(rel, out);
    } else if (/\.(tsx|ts)$/.test(name.name)) out.push(rel);
  }
  return out;
}
const iconNames = new Set();
for (const file of walkFiles("src")) {
  const source = readFileSync(join(ROOT, file), "utf8");
  for (const m of source.matchAll(/import\s*\{([^}]*)\}\s*from\s*["']@tabler\/icons-react["']/g)) {
    for (const part of m[1].split(",")) {
      const name = part.trim().split(/\s+as\s+/)[0].trim();
      if (/^Icon[A-Z0-9]\w*$/.test(name)) iconNames.add(name);
    }
  }
}
const TABLER = [join(ROOT, "node_modules/@tabler/icons-react/dist/esm/icons")];
const toPath = (tag, a) => {
  const n = (k) => Number(a[k] ?? 0);
  switch (tag) {
    case "path":
      return a.d;
    case "line":
      return `M${n("x1")} ${n("y1")}L${n("x2")} ${n("y2")}`;
    case "polyline":
    case "polygon": {
      const pts = a.points.trim().split(/[\s,]+/).map(Number);
      let d = `M${pts[0]} ${pts[1]}`;
      for (let i = 2; i < pts.length; i += 2) d += `L${pts[i]} ${pts[i + 1]}`;
      return tag === "polygon" ? `${d}Z` : d;
    }
    case "circle":
    case "ellipse": {
      const cx = n("cx");
      const cy = n("cy");
      const rx = tag === "circle" ? n("r") : n("rx");
      const ry = tag === "circle" ? n("r") : n("ry");
      return `M${cx - rx} ${cy}a${rx} ${ry} 0 1 0 ${2 * rx} 0a${rx} ${ry} 0 1 0 ${-2 * rx} 0`;
    }
    case "rect": {
      const x = n("x");
      const y = n("y");
      const w = n("width");
      const h = n("height");
      const r = Math.min(Number(a.rx ?? a.ry ?? 0), w / 2, h / 2);
      if (!r) return `M${x} ${y}h${w}v${h}h${-w}Z`;
      return `M${x + r} ${y}h${w - 2 * r}a${r} ${r} 0 0 1 ${r} ${r}v${h - 2 * r}a${r} ${r} 0 0 1 ${-r} ${r}h${-(w - 2 * r)}a${r} ${r} 0 0 1 ${-r} ${-r}v${-(h - 2 * r)}a${r} ${r} 0 0 1 ${r} ${-r}Z`;
    }
    default:
      return null;
  }
};
const iconEntries = [];
if (existsSync(TABLER[0])) {
  for (const name of [...iconNames].sort()) {
    const file = join(TABLER[0], `${name}.mjs`);
    if (!existsSync(file)) continue;
    const src = readFileSync(file, "utf8");
    const nodes = JSON.parse(src.match(/const __iconNode = (\[[\s\S]*?\]);\n/)[1]);
    const filled = /createReactComponent\("filled"/.test(src);
    const paths = nodes.map(([tag, attrs]) => toPath(tag, attrs)).filter(Boolean);
    iconEntries.push({ name: name.replace(/^Icon/, ""), filled, paths });
  }
  const kt = [
    `// ${HEADER}`,
    "// Tabler icons (MIT) used by the web app — same artwork on Android and iPhone.",
    "package dk.packroff.hellocal.ui.icons",
    "",
    "internal object TablerData {",
    "    /** name → (filled, SVG path data on a 24×24 grid) */",
    "    val icons: Map<String, Pair<Boolean, List<String>>> = mapOf(",
    ...iconEntries.map((e) => `        ${JSON.stringify(e.name)} to (${e.filled} to listOf(${e.paths.map((p) => JSON.stringify(p).replace(/\$/g, "\\$")).join(", ")})),`),
    "    )",
    "}",
    "",
  ].join("\n");
  outputs.set("native/shared/src/commonMain/kotlin/dk/packroff/hellocal/ui/icons/TablerData.kt", kt);
}

// ---- binary assets copied 1:1 (app icon) ---------------------------------
const binaries = new Map([["native/androidApp/src/main/res/mipmap-xxxhdpi/ic_launcher.png", "src/app/icon.png"]]);

let stale = [];
for (const [rel, srcRel] of binaries) {
  const abs = join(ROOT, rel);
  const want = readFileSync(join(ROOT, srcRel));
  if (existsSync(abs) && Buffer.compare(readFileSync(abs), want) === 0) continue;
  stale.push(rel);
  if (!CHECK) {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, want);
  }
}
for (const [rel, content] of outputs) {
  const abs = join(ROOT, rel);
  const current = existsSync(abs) ? readFileSync(abs, "utf8").replace(/\r\n/g, "\n") : null;
  if (current === content) continue;
  stale.push(rel);
  if (!CHECK) {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
  }
}

if (CHECK) {
  if (stale.length) {
    console.error(`Native-filer er ikke i takt med web — kør: node scripts/native/sync.mjs\n${stale.map((s) => `  ${s}`).join("\n")}`);
    process.exit(1);
  }
  console.log("Native farver/typografi/tekster er i takt med web.");
} else {
  console.log(stale.length ? `Opdaterede ${stale.length} filer:\n${stale.map((s) => `  ${s}`).join("\n")}` : "Alt var allerede i takt.");
  console.log(`${colorList.length} farver, ${dimList.length} mål, ${typeList.length} tekstroller, ${[...outputs.keys()].filter((k) => k.includes("/locales/")).length} sprog, ${iconEntries.length} ikoner.`);
}
